platform :ios, '8.0'
source 'https://github.com/iSpeakSwift/spec.git'
source 'https://github.com/iSpeakSwift/pod-library'

use_frameworks!

target 'pod-library_Example' do
  pod 'pod-library', :path => '../'

  target 'pod-library_Tests' do
    inherit! :search_paths

    
  end
end
